package com.onecric.live.model;

public class AnchorBean {
    public Integer birthday;
    public int heat;
    public int isAnchor;
    public int postNum;
    public long lastLoginTime;
    public long deletetime;
    public String signature;
    public int channel;
    public int isExpert;
    public String withdrawalBalance;
    public int score;
    public int userType;
    public String balance;
    public String lastLoginIp;
    public String userLogin;
    public String userNickname;
    public String userUrl;
    public int isWriter;
    public int giveAway;
    public int id;
    public String userActivationKey;
    public Integer exp;
    public Integer userStatus;
    public String userEmail;
    public int votestotal;
    public long createTime;
    public int sex;
    public String mobile;
    public String freezeBalance;
    public String avatar;
    public int articleNum;
    public int attention;
    public int videoNum;
    public long updatetime;
    public int coin;
    public String userPass;
    public int isLive;
    public String onlineTime;
    public int isAttention;
}
