package com.onecric.live.model;

public class OneHistoryLiveBean {
    public String venue;
    public String awayName;
    public String homeDisplayScore;
    public String scheduled;
    public String startTimeTbd;
    public Double homeWinProbabilities;
    public Integer channel;
    public int winnerId;
    public String createdAt;
    public Integer starttime;
    public int tournamentId;
    public String matchResultType;
    public int awayId;
    public int uid;
    public String matchNum;
    public String updatedAt;
    public String awayDisplayScore;
    public String homeName;
    public String matchResult;
    public int homeId;
    public int id;
    public int matchId;
    public Integer liveStatus;
    public String awayLogo;
    public String liveTime;
    public String mediaUrl;
    public String tournamentRound;
    public int seasonId;
    public String todaystart;
    public String matchStatus;
    public Double awayWinProbabilities;
    public int liveId;
    public Integer viewers;
    public String homeLogo;
    public Integer matchDays;
    public int liveUid;
    public Long liveTimeUnix;
    public Integer matchDay;
    public Integer status;
}
